//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class bangtinhphi
    {
        public int BangTinhPhiId { get; set; }
        public int SoNgayNghiMin { get; set; }
        public int SoNgayNghiMax { get; set; }
        public long SoTien { get; set; }
        public int KhoanThuId { get; set; }
        public int KhoiId { get; set; }
    }
}
