//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoctap
    {
        public int HocTapId { get; set; }
        public int HocSinhLopId { get; set; }
        public Nullable<bool> Hoc2Buoi { get; set; }
        public string ChuyenCan { get; set; }
        public Nullable<bool> AnTaiTruong { get; set; }
        public string HocLienTuc { get; set; }
        public string TheoDoiCanNang { get; set; }
        public string SDDCanNang { get; set; }
        public string TheoDoiChieuCao { get; set; }
        public string SDDChieuCao { get; set; }
        public Nullable<bool> HoanThanhCTGDMN { get; set; }
        public string DanhGia { get; set; }
    }
}
