//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuthu
    {
        public int PhieuThuId { get; set; }
        public System.DateTime Ngay { get; set; }
        public long SoTien { get; set; }
        public string PaymentType { get; set; }
        public string MaPhieu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> PhanLoaiThuId { get; set; }
        public Nullable<int> HocSinhId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
