//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class phieuchi
    {
        public int PhieuChiId { get; set; }
        public string MaPhieu { get; set; }
        public DateTime Ngay { get; set; }
        public long SoTien { get; set; }
        public string GhiChu { get; set; }
        public int PhanLoaiChiId { get; set; }
        public string NoiDung { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public DateTime CreatedDate { get; set; }

        [NotMapped]
        public string DienGiai { get; set; }

        [NotMapped]
        public string MaPhanLoai { get; set; }

        [NotMapped]
        public string PhanLoaiChi { get; set; }
    }
}
