//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class qlmamnonEntities : DbContext
    {
        public qlmamnonEntities()
            : base("name=qlmamnonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bangthutien> bangthutiens { get; set; }
        public virtual DbSet<bangthutien_khoanthu> bangthutien_khoanthu { get; set; }
        public virtual DbSet<bangthutiengenhistory> bangthutiengenhistories { get; set; }
        public virtual DbSet<bangtinhphi> bangtinhphis { get; set; }
        public virtual DbSet<baocaothang> baocaothangs { get; set; }
        public virtual DbSet<baocaothanggenhistory> baocaothanggenhistories { get; set; }
        public virtual DbSet<hocsinh> hocsinhs { get; set; }
        public virtual DbSet<hocsinh_lop> hocsinh_lop { get; set; }
        public virtual DbSet<hoctap> hoctaps { get; set; }
        public virtual DbSet<khoanthu> khoanthus { get; set; }
        public virtual DbSet<khoanthuhangnam> khoanthuhangnams { get; set; }
        public virtual DbSet<khoi> khois { get; set; }
        public virtual DbSet<khoi_truong> khoi_truong { get; set; }
        public virtual DbSet<lop> lops { get; set; }
        public virtual DbSet<lop_khoi> lop_khoi { get; set; }
        public virtual DbSet<phanloaichi> phanloaichis { get; set; }
        public virtual DbSet<phanloaithu> phanloaithus { get; set; }
        public virtual DbSet<phieuchi> phieuchis { get; set; }
        public virtual DbSet<phieuthu> phieuthus { get; set; }
        public virtual DbSet<phuongxa> phuongxas { get; set; }
        public virtual DbSet<privilege> privileges { get; set; }
        public virtual DbSet<quanhuyen> quanhuyens { get; set; }
        public virtual DbSet<schoolsetting> schoolsettings { get; set; }
        public virtual DbSet<smstemplate> smstemplates { get; set; }
        public virtual DbSet<taisan> taisans { get; set; }
        public virtual DbSet<taisan_lop> taisan_lop { get; set; }
        public virtual DbSet<thanhpho> thanhphoes { get; set; }
        public virtual DbSet<truong> truongs { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_privilege> user_privilege { get; set; }
        public virtual DbSet<viewbangiaotaisan> viewbangiaotaisans { get; set; }
        public virtual DbSet<viewbangthutien> viewbangthutiens { get; set; }
        public virtual DbSet<viewhoctap> viewhoctaps { get; set; }
        public virtual DbSet<viewtaisan> viewtaisans { get; set; }
        public virtual DbSet<viewtaisanforbangiaotaisan> viewtaisanforbangiaotaisans { get; set; }
    
        public virtual int deleteBangThuTienByHocSinhIdsAndDate(string p_hocsinhids, Nullable<System.DateTime> p_date)
        {
            var p_hocsinhidsParameter = p_hocsinhids != null ?
                new ObjectParameter("hocsinhids", p_hocsinhids) :
                new ObjectParameter("hocsinhids", typeof(string));
    
            var p_dateParameter = p_date.HasValue ?
                new ObjectParameter("date", p_date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteBangThuTienByHocSinhIdsAndDate", p_hocsinhidsParameter, p_dateParameter);
        }
    
        public virtual int deleteBangThuTienById(Nullable<int> p_bangthutienid)
        {
            var p_bangthutienidParameter = p_bangthutienid.HasValue ?
                new ObjectParameter("bangthutienid", p_bangthutienid) :
                new ObjectParameter("bangthutienid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteBangThuTienById", p_bangthutienidParameter);
        }
    
        public virtual int deleteBangThuTienKhoanThuByBangThuTienId(Nullable<int> p_bangthutienid)
        {
            var p_bangthutienidParameter = p_bangthutienid.HasValue ?
                new ObjectParameter("bangthutienid", p_bangthutienid) :
                new ObjectParameter("bangthutienid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteBangThuTienKhoanThuByBangThuTienId", p_bangthutienidParameter);
        }
    
        public virtual int deleteHocSinhLopByHocSinhIds(string hocsinhids, Nullable<System.DateTime> deleteddate)
        {
            var hocsinhidsParameter = hocsinhids != null ?
                new ObjectParameter("hocsinhids", hocsinhids) :
                new ObjectParameter("hocsinhids", typeof(string));
    
            var deleteddateParameter = deleteddate.HasValue ?
                new ObjectParameter("deleteddate", deleteddate) :
                new ObjectParameter("deleteddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteHocSinhLopByHocSinhIds", hocsinhidsParameter, deleteddateParameter);
        }
    
        public virtual int deleteKhoiTruongByKhoiId(Nullable<int> khoi)
        {
            var khoiParameter = khoi.HasValue ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteKhoiTruongByKhoiId", khoiParameter);
        }
    
        public virtual int deleteLopKhoiByLopId(Nullable<int> lop)
        {
            var lopParameter = lop.HasValue ?
                new ObjectParameter("lop", lop) :
                new ObjectParameter("lop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteLopKhoiByLopId", lopParameter);
        }
    
        public virtual int deleteUserPrivileges(string p_notinprivilegeids, Nullable<int> p_userid)
        {
            var p_notinprivilegeidsParameter = p_notinprivilegeids != null ?
                new ObjectParameter("notinprivilegeids", p_notinprivilegeids) :
                new ObjectParameter("notinprivilegeids", typeof(string));
    
            var p_useridParameter = p_userid.HasValue ?
                new ObjectParameter("userid", p_userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteUserPrivileges", p_notinprivilegeidsParameter, p_useridParameter);
        }
    
        public virtual int deleteViewBanGiaoTaiSan(Nullable<int> taisanlopid)
        {
            var taisanlopidParameter = taisanlopid.HasValue ?
                new ObjectParameter("taisanlopid", taisanlopid) :
                new ObjectParameter("taisanlopid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteViewBanGiaoTaiSan", taisanlopidParameter);
        }
    
        public virtual int deleteViewTaiSan(Nullable<int> taisanid)
        {
            var taisanidParameter = taisanid.HasValue ?
                new ObjectParameter("taisanid", taisanid) :
                new ObjectParameter("taisanid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteViewTaiSan", taisanidParameter);
        }
    
        public virtual ObjectResult<bangthutien> getBangThuTienById(Nullable<int> p_bangthutienid)
        {
            var p_bangthutienidParameter = p_bangthutienid.HasValue ?
                new ObjectParameter("bangthutienid", p_bangthutienid) :
                new ObjectParameter("bangthutienid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bangthutien>("getBangThuTienById", p_bangthutienidParameter);
        }
    
        public virtual ObjectResult<bangthutien> getBangThuTienById(Nullable<int> p_bangthutienid, MergeOption mergeOption)
        {
            var p_bangthutienidParameter = p_bangthutienid.HasValue ?
                new ObjectParameter("bangthutienid", p_bangthutienid) :
                new ObjectParameter("bangthutienid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bangthutien>("getBangThuTienById", mergeOption, p_bangthutienidParameter);
        }
    
        public virtual ObjectResult<bangthutiengenhistory> getBangThuTienGenHistoryByLopAndNgay(Nullable<int> p_lopid, Nullable<System.DateTime> p_ngay)
        {
            var p_lopidParameter = p_lopid.HasValue ?
                new ObjectParameter("lopid", p_lopid) :
                new ObjectParameter("lopid", typeof(int));
    
            var p_ngayParameter = p_ngay.HasValue ?
                new ObjectParameter("ngay", p_ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bangthutiengenhistory>("getBangThuTienGenHistoryByLopAndNgay", p_lopidParameter, p_ngayParameter);
        }
    
        public virtual ObjectResult<bangthutiengenhistory> getBangThuTienGenHistoryByLopAndNgay(Nullable<int> p_lopid, Nullable<System.DateTime> p_ngay, MergeOption mergeOption)
        {
            var p_lopidParameter = p_lopid.HasValue ?
                new ObjectParameter("lopid", p_lopid) :
                new ObjectParameter("lopid", typeof(int));
    
            var p_ngayParameter = p_ngay.HasValue ?
                new ObjectParameter("ngay", p_ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bangthutiengenhistory>("getBangThuTienGenHistoryByLopAndNgay", mergeOption, p_lopidParameter, p_ngayParameter);
        }
    
        public virtual ObjectResult<bangthutien_khoanthu> getBangThuTienKhoanThuByBangThuTienIds(string bangthutienids)
        {
            var bangthutienidsParameter = bangthutienids != null ?
                new ObjectParameter("bangthutienids", bangthutienids) :
                new ObjectParameter("bangthutienids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bangthutien_khoanthu>("getBangThuTienKhoanThuByBangThuTienIds", bangthutienidsParameter);
        }
    
        public virtual ObjectResult<bangthutien_khoanthu> getBangThuTienKhoanThuByBangThuTienIds(string bangthutienids, MergeOption mergeOption)
        {
            var bangthutienidsParameter = bangthutienids != null ?
                new ObjectParameter("bangthutienids", bangthutienids) :
                new ObjectParameter("bangthutienids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bangthutien_khoanthu>("getBangThuTienKhoanThuByBangThuTienIds", mergeOption, bangthutienidsParameter);
        }
    
        public virtual ObjectResult<hocsinh> getHocSinhByLopAndNgay(Nullable<int> lop, Nullable<System.DateTime> ngay)
        {
            var lopParameter = lop.HasValue ?
                new ObjectParameter("lop", lop) :
                new ObjectParameter("lop", typeof(int));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hocsinh>("getHocSinhByLopAndNgay", lopParameter, ngayParameter);
        }
    
        public virtual ObjectResult<hocsinh> getHocSinhByLopAndNgay(Nullable<int> lop, Nullable<System.DateTime> ngay, MergeOption mergeOption)
        {
            var lopParameter = lop.HasValue ?
                new ObjectParameter("lop", lop) :
                new ObjectParameter("lop", typeof(int));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hocsinh>("getHocSinhByLopAndNgay", mergeOption, lopParameter, ngayParameter);
        }
    
        public virtual ObjectResult<hocsinh> getHocSinhByParams(Nullable<System.DateTime> ngay, Nullable<int> khoihoc, Nullable<int> lophoc, Nullable<System.DateTime> ngayvaolop)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var khoihocParameter = khoihoc.HasValue ?
                new ObjectParameter("khoihoc", khoihoc) :
                new ObjectParameter("khoihoc", typeof(int));
    
            var lophocParameter = lophoc.HasValue ?
                new ObjectParameter("lophoc", lophoc) :
                new ObjectParameter("lophoc", typeof(int));
    
            var ngayvaolopParameter = ngayvaolop.HasValue ?
                new ObjectParameter("ngayvaolop", ngayvaolop) :
                new ObjectParameter("ngayvaolop", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hocsinh>("getHocSinhByParams", ngayParameter, khoihocParameter, lophocParameter, ngayvaolopParameter);
        }
    
        public virtual ObjectResult<hocsinh> getHocSinhByParams(Nullable<System.DateTime> ngay, Nullable<int> khoihoc, Nullable<int> lophoc, Nullable<System.DateTime> ngayvaolop, MergeOption mergeOption)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var khoihocParameter = khoihoc.HasValue ?
                new ObjectParameter("khoihoc", khoihoc) :
                new ObjectParameter("khoihoc", typeof(int));
    
            var lophocParameter = lophoc.HasValue ?
                new ObjectParameter("lophoc", lophoc) :
                new ObjectParameter("lophoc", typeof(int));
    
            var ngayvaolopParameter = ngayvaolop.HasValue ?
                new ObjectParameter("ngayvaolop", ngayvaolop) :
                new ObjectParameter("ngayvaolop", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hocsinh>("getHocSinhByParams", mergeOption, ngayParameter, khoihocParameter, lophocParameter, ngayvaolopParameter);
        }
    
        public virtual ObjectResult<hocsinh> getHocSinhForThongTinHocSinh(Nullable<int> p_quan, Nullable<int> p_phuong, Nullable<System.DateTime> p_ngaysinh, Nullable<int> p_thangsinh, Nullable<int> p_lop, Nullable<bool> p_thoihoc, Nullable<int> p_namsinh)
        {
            var p_quanParameter = p_quan.HasValue ?
                new ObjectParameter("quan", p_quan) :
                new ObjectParameter("quan", typeof(int));
    
            var p_phuongParameter = p_phuong.HasValue ?
                new ObjectParameter("phuong", p_phuong) :
                new ObjectParameter("phuong", typeof(int));
    
            var p_ngaysinhParameter = p_ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", p_ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var p_thangsinhParameter = p_thangsinh.HasValue ?
                new ObjectParameter("thangsinh", p_thangsinh) :
                new ObjectParameter("thangsinh", typeof(int));
    
            var p_lopParameter = p_lop.HasValue ?
                new ObjectParameter("lop", p_lop) :
                new ObjectParameter("lop", typeof(int));
    
            var p_thoihocParameter = p_thoihoc.HasValue ?
                new ObjectParameter("thoihoc", p_thoihoc) :
                new ObjectParameter("thoihoc", typeof(bool));
    
            var p_namsinhParameter = p_namsinh.HasValue ?
                new ObjectParameter("namsinh", p_namsinh) :
                new ObjectParameter("namsinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hocsinh>("getHocSinhForThongTinHocSinh", p_quanParameter, p_phuongParameter, p_ngaysinhParameter, p_thangsinhParameter, p_lopParameter, p_thoihocParameter, p_namsinhParameter);
        }
    
        public virtual ObjectResult<hocsinh> getHocSinhForThongTinHocSinh(Nullable<int> p_quan, Nullable<int> p_phuong, Nullable<System.DateTime> p_ngaysinh, Nullable<int> p_thangsinh, Nullable<int> p_lop, Nullable<bool> p_thoihoc, Nullable<int> p_namsinh, MergeOption mergeOption)
        {
            var p_quanParameter = p_quan.HasValue ?
                new ObjectParameter("quan", p_quan) :
                new ObjectParameter("quan", typeof(int));
    
            var p_phuongParameter = p_phuong.HasValue ?
                new ObjectParameter("phuong", p_phuong) :
                new ObjectParameter("phuong", typeof(int));
    
            var p_ngaysinhParameter = p_ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", p_ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var p_thangsinhParameter = p_thangsinh.HasValue ?
                new ObjectParameter("thangsinh", p_thangsinh) :
                new ObjectParameter("thangsinh", typeof(int));
    
            var p_lopParameter = p_lop.HasValue ?
                new ObjectParameter("lop", p_lop) :
                new ObjectParameter("lop", typeof(int));
    
            var p_thoihocParameter = p_thoihoc.HasValue ?
                new ObjectParameter("thoihoc", p_thoihoc) :
                new ObjectParameter("thoihoc", typeof(bool));
    
            var p_namsinhParameter = p_namsinh.HasValue ?
                new ObjectParameter("namsinh", p_namsinh) :
                new ObjectParameter("namsinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hocsinh>("getHocSinhForThongTinHocSinh", mergeOption, p_quanParameter, p_phuongParameter, p_ngaysinhParameter, p_thangsinhParameter, p_lopParameter, p_thoihocParameter, p_namsinhParameter);
        }
    
        public virtual ObjectResult<hocsinh_lop> getHocSinhLopByHocSinhIdsAndNgay(string hocsinhids, Nullable<System.DateTime> ngay)
        {
            var hocsinhidsParameter = hocsinhids != null ?
                new ObjectParameter("hocsinhids", hocsinhids) :
                new ObjectParameter("hocsinhids", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hocsinh_lop>("getHocSinhLopByHocSinhIdsAndNgay", hocsinhidsParameter, ngayParameter);
        }
    
        public virtual ObjectResult<hocsinh_lop> getHocSinhLopByHocSinhIdsAndNgay(string hocsinhids, Nullable<System.DateTime> ngay, MergeOption mergeOption)
        {
            var hocsinhidsParameter = hocsinhids != null ?
                new ObjectParameter("hocsinhids", hocsinhids) :
                new ObjectParameter("hocsinhids", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hocsinh_lop>("getHocSinhLopByHocSinhIdsAndNgay", mergeOption, hocsinhidsParameter, ngayParameter);
        }
    
        public virtual ObjectResult<hocsinh> getHocSinhNotAssignedToLop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hocsinh>("getHocSinhNotAssignedToLop");
        }
    
        public virtual ObjectResult<hocsinh> getHocSinhNotAssignedToLop(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hocsinh>("getHocSinhNotAssignedToLop", mergeOption);
        }
    
        public virtual ObjectResult<khoanthu> getKhoanThuByIds(string khoanthuids)
        {
            var khoanthuidsParameter = khoanthuids != null ?
                new ObjectParameter("khoanthuids", khoanthuids) :
                new ObjectParameter("khoanthuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<khoanthu>("getKhoanThuByIds", khoanthuidsParameter);
        }
    
        public virtual ObjectResult<khoanthu> getKhoanThuByIds(string khoanthuids, MergeOption mergeOption)
        {
            var khoanthuidsParameter = khoanthuids != null ?
                new ObjectParameter("khoanthuids", khoanthuids) :
                new ObjectParameter("khoanthuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<khoanthu>("getKhoanThuByIds", mergeOption, khoanthuidsParameter);
        }
    
        public virtual ObjectResult<khoanthuhangnam> getKhoanThuHangNamByParams(string khoanthuids, Nullable<int> khoi, Nullable<System.DateTime> ngay)
        {
            var khoanthuidsParameter = khoanthuids != null ?
                new ObjectParameter("khoanthuids", khoanthuids) :
                new ObjectParameter("khoanthuids", typeof(string));
    
            var khoiParameter = khoi.HasValue ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(int));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<khoanthuhangnam>("getKhoanThuHangNamByParams", khoanthuidsParameter, khoiParameter, ngayParameter);
        }
    
        public virtual ObjectResult<khoanthuhangnam> getKhoanThuHangNamByParams(string khoanthuids, Nullable<int> khoi, Nullable<System.DateTime> ngay, MergeOption mergeOption)
        {
            var khoanthuidsParameter = khoanthuids != null ?
                new ObjectParameter("khoanthuids", khoanthuids) :
                new ObjectParameter("khoanthuids", typeof(string));
    
            var khoiParameter = khoi.HasValue ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(int));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<khoanthuhangnam>("getKhoanThuHangNamByParams", mergeOption, khoanthuidsParameter, khoiParameter, ngayParameter);
        }
    
        public virtual ObjectResult<khoi_truong> getKhoiTruongByKhoiId(Nullable<int> khoi)
        {
            var khoiParameter = khoi.HasValue ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<khoi_truong>("getKhoiTruongByKhoiId", khoiParameter);
        }
    
        public virtual ObjectResult<khoi_truong> getKhoiTruongByKhoiId(Nullable<int> khoi, MergeOption mergeOption)
        {
            var khoiParameter = khoi.HasValue ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<khoi_truong>("getKhoiTruongByKhoiId", mergeOption, khoiParameter);
        }
    
        public virtual ObjectResult<lop_khoi> getLopKhoiByLopId(Nullable<int> lop)
        {
            var lopParameter = lop.HasValue ?
                new ObjectParameter("lop", lop) :
                new ObjectParameter("lop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lop_khoi>("getLopKhoiByLopId", lopParameter);
        }
    
        public virtual ObjectResult<lop_khoi> getLopKhoiByLopId(Nullable<int> lop, MergeOption mergeOption)
        {
            var lopParameter = lop.HasValue ?
                new ObjectParameter("lop", lop) :
                new ObjectParameter("lop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lop_khoi>("getLopKhoiByLopId", mergeOption, lopParameter);
        }
    
        public virtual ObjectResult<phieuchi> getPhieuChiByDateRange(Nullable<System.DateTime> p_fromDate, Nullable<System.DateTime> p_toDate, string p_phanloaichiids)
        {
            var p_fromDateParameter = p_fromDate.HasValue ?
                new ObjectParameter("fromDate", p_fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var p_toDateParameter = p_toDate.HasValue ?
                new ObjectParameter("toDate", p_toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var p_phanloaichiidsParameter = p_phanloaichiids != null ?
                new ObjectParameter("phanloaichiids", p_phanloaichiids) :
                new ObjectParameter("phanloaichiids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuchi>("getPhieuChiByDateRange", p_fromDateParameter, p_toDateParameter, p_phanloaichiidsParameter);
        }
    
        public virtual ObjectResult<phieuchi> getPhieuChiByDateRange(Nullable<System.DateTime> p_fromDate, Nullable<System.DateTime> p_toDate, string p_phanloaichiids, MergeOption mergeOption)
        {
            var p_fromDateParameter = p_fromDate.HasValue ?
                new ObjectParameter("fromDate", p_fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var p_toDateParameter = p_toDate.HasValue ?
                new ObjectParameter("toDate", p_toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var p_phanloaichiidsParameter = p_phanloaichiids != null ?
                new ObjectParameter("phanloaichiids", p_phanloaichiids) :
                new ObjectParameter("phanloaichiids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuchi>("getPhieuChiByDateRange", mergeOption, p_fromDateParameter, p_toDateParameter, p_phanloaichiidsParameter);
        }
    
        public virtual ObjectResult<phieuchi> getPhieuChiByDateRangeWithGroupPhanLoaiChi(Nullable<System.DateTime> p_fromDate, Nullable<System.DateTime> p_toDate, string p_phanloaichiids)
        {
            var p_fromDateParameter = p_fromDate.HasValue ?
                new ObjectParameter("fromDate", p_fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var p_toDateParameter = p_toDate.HasValue ?
                new ObjectParameter("toDate", p_toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var p_phanloaichiidsParameter = p_phanloaichiids != null ?
                new ObjectParameter("phanloaichiids", p_phanloaichiids) :
                new ObjectParameter("phanloaichiids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuchi>("getPhieuChiByDateRangeWithGroupPhanLoaiChi", p_fromDateParameter, p_toDateParameter, p_phanloaichiidsParameter);
        }
    
        public virtual ObjectResult<phieuchi> getPhieuChiByDateRangeWithGroupPhanLoaiChi(Nullable<System.DateTime> p_fromDate, Nullable<System.DateTime> p_toDate, string p_phanloaichiids, MergeOption mergeOption)
        {
            var p_fromDateParameter = p_fromDate.HasValue ?
                new ObjectParameter("fromDate", p_fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var p_toDateParameter = p_toDate.HasValue ?
                new ObjectParameter("toDate", p_toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var p_phanloaichiidsParameter = p_phanloaichiids != null ?
                new ObjectParameter("phanloaichiids", p_phanloaichiids) :
                new ObjectParameter("phanloaichiids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuchi>("getPhieuChiByDateRangeWithGroupPhanLoaiChi", mergeOption, p_fromDateParameter, p_toDateParameter, p_phanloaichiidsParameter);
        }
    
        public virtual ObjectResult<phieuchi> getPhieuChiById(Nullable<int> phieuchiid)
        {
            var phieuchiidParameter = phieuchiid.HasValue ?
                new ObjectParameter("phieuchiid", phieuchiid) :
                new ObjectParameter("phieuchiid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuchi>("getPhieuChiById", phieuchiidParameter);
        }
    
        public virtual ObjectResult<phieuchi> getPhieuChiById(Nullable<int> phieuchiid, MergeOption mergeOption)
        {
            var phieuchiidParameter = phieuchiid.HasValue ?
                new ObjectParameter("phieuchiid", phieuchiid) :
                new ObjectParameter("phieuchiid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuchi>("getPhieuChiById", mergeOption, phieuchiidParameter);
        }
    
        public virtual ObjectResult<phieuchi> getPhieuChiListForReportBCHDTC(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string phanloaichiids)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var phanloaichiidsParameter = phanloaichiids != null ?
                new ObjectParameter("phanloaichiids", phanloaichiids) :
                new ObjectParameter("phanloaichiids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuchi>("getPhieuChiListForReportBCHDTC", tungayParameter, denngayParameter, phanloaichiidsParameter);
        }
    
        public virtual ObjectResult<phieuchi> getPhieuChiListForReportBCHDTC(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string phanloaichiids, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var phanloaichiidsParameter = phanloaichiids != null ?
                new ObjectParameter("phanloaichiids", phanloaichiids) :
                new ObjectParameter("phanloaichiids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuchi>("getPhieuChiListForReportBCHDTC", mergeOption, tungayParameter, denngayParameter, phanloaichiidsParameter);
        }
    
        public virtual ObjectResult<phieuthu> getPhieuThuByDateRangeWithGroupPhanLoaiThu(Nullable<System.DateTime> p_fromDate, Nullable<System.DateTime> p_toDate, string p_phanloaithuids)
        {
            var p_fromDateParameter = p_fromDate.HasValue ?
                new ObjectParameter("fromDate", p_fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var p_toDateParameter = p_toDate.HasValue ?
                new ObjectParameter("toDate", p_toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var p_phanloaithuidsParameter = p_phanloaithuids != null ?
                new ObjectParameter("phanloaithuids", p_phanloaithuids) :
                new ObjectParameter("phanloaithuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuthu>("getPhieuThuByDateRangeWithGroupPhanLoaiThu", p_fromDateParameter, p_toDateParameter, p_phanloaithuidsParameter);
        }
    
        public virtual ObjectResult<phieuthu> getPhieuThuByDateRangeWithGroupPhanLoaiThu(Nullable<System.DateTime> p_fromDate, Nullable<System.DateTime> p_toDate, string p_phanloaithuids, MergeOption mergeOption)
        {
            var p_fromDateParameter = p_fromDate.HasValue ?
                new ObjectParameter("fromDate", p_fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var p_toDateParameter = p_toDate.HasValue ?
                new ObjectParameter("toDate", p_toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var p_phanloaithuidsParameter = p_phanloaithuids != null ?
                new ObjectParameter("phanloaithuids", p_phanloaithuids) :
                new ObjectParameter("phanloaithuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuthu>("getPhieuThuByDateRangeWithGroupPhanLoaiThu", mergeOption, p_fromDateParameter, p_toDateParameter, p_phanloaithuidsParameter);
        }
    
        public virtual ObjectResult<phieuthu> getPhieuThuByHocSinhIdAndNgayTinh(Nullable<int> hocsinhid, Nullable<System.DateTime> ngaytinh)
        {
            var hocsinhidParameter = hocsinhid.HasValue ?
                new ObjectParameter("hocsinhid", hocsinhid) :
                new ObjectParameter("hocsinhid", typeof(int));
    
            var ngaytinhParameter = ngaytinh.HasValue ?
                new ObjectParameter("ngaytinh", ngaytinh) :
                new ObjectParameter("ngaytinh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuthu>("getPhieuThuByHocSinhIdAndNgayTinh", hocsinhidParameter, ngaytinhParameter);
        }
    
        public virtual ObjectResult<phieuthu> getPhieuThuByHocSinhIdAndNgayTinh(Nullable<int> hocsinhid, Nullable<System.DateTime> ngaytinh, MergeOption mergeOption)
        {
            var hocsinhidParameter = hocsinhid.HasValue ?
                new ObjectParameter("hocsinhid", hocsinhid) :
                new ObjectParameter("hocsinhid", typeof(int));
    
            var ngaytinhParameter = ngaytinh.HasValue ?
                new ObjectParameter("ngaytinh", ngaytinh) :
                new ObjectParameter("ngaytinh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuthu>("getPhieuThuByHocSinhIdAndNgayTinh", mergeOption, hocsinhidParameter, ngaytinhParameter);
        }
    
        public virtual ObjectResult<phieuthu> getPhieuThuForSoQuyTienMat(Nullable<System.DateTime> p_fromDate, Nullable<System.DateTime> p_toDate, string p_phanloaithuids)
        {
            var p_fromDateParameter = p_fromDate.HasValue ?
                new ObjectParameter("fromDate", p_fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var p_toDateParameter = p_toDate.HasValue ?
                new ObjectParameter("toDate", p_toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var p_phanloaithuidsParameter = p_phanloaithuids != null ?
                new ObjectParameter("phanloaithuids", p_phanloaithuids) :
                new ObjectParameter("phanloaithuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuthu>("getPhieuThuForSoQuyTienMat", p_fromDateParameter, p_toDateParameter, p_phanloaithuidsParameter);
        }
    
        public virtual ObjectResult<phieuthu> getPhieuThuForSoQuyTienMat(Nullable<System.DateTime> p_fromDate, Nullable<System.DateTime> p_toDate, string p_phanloaithuids, MergeOption mergeOption)
        {
            var p_fromDateParameter = p_fromDate.HasValue ?
                new ObjectParameter("fromDate", p_fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var p_toDateParameter = p_toDate.HasValue ?
                new ObjectParameter("toDate", p_toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var p_phanloaithuidsParameter = p_phanloaithuids != null ?
                new ObjectParameter("phanloaithuids", p_phanloaithuids) :
                new ObjectParameter("phanloaithuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuthu>("getPhieuThuForSoQuyTienMat", mergeOption, p_fromDateParameter, p_toDateParameter, p_phanloaithuidsParameter);
        }
    
        public virtual ObjectResult<phieuthu> getPhieuThuOfMonthByHocSinhIdsAndNgay(string p_hocsinhids, Nullable<System.DateTime> p_ngay)
        {
            var p_hocsinhidsParameter = p_hocsinhids != null ?
                new ObjectParameter("hocsinhids", p_hocsinhids) :
                new ObjectParameter("hocsinhids", typeof(string));
    
            var p_ngayParameter = p_ngay.HasValue ?
                new ObjectParameter("ngay", p_ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuthu>("getPhieuThuOfMonthByHocSinhIdsAndNgay", p_hocsinhidsParameter, p_ngayParameter);
        }
    
        public virtual ObjectResult<phieuthu> getPhieuThuOfMonthByHocSinhIdsAndNgay(string p_hocsinhids, Nullable<System.DateTime> p_ngay, MergeOption mergeOption)
        {
            var p_hocsinhidsParameter = p_hocsinhids != null ?
                new ObjectParameter("hocsinhids", p_hocsinhids) :
                new ObjectParameter("hocsinhids", typeof(string));
    
            var p_ngayParameter = p_ngay.HasValue ?
                new ObjectParameter("ngay", p_ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<phieuthu>("getPhieuThuOfMonthByHocSinhIdsAndNgay", mergeOption, p_hocsinhidsParameter, p_ngayParameter);
        }
    
        public virtual ObjectResult<getSoNgayNghiThangByNgayAndHocSinhIds_Result> getSoNgayNghiThangByNgayAndHocSinhIds(string hocsinhids, Nullable<System.DateTime> ngay)
        {
            var hocsinhidsParameter = hocsinhids != null ?
                new ObjectParameter("hocsinhids", hocsinhids) :
                new ObjectParameter("hocsinhids", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSoNgayNghiThangByNgayAndHocSinhIds_Result>("getSoNgayNghiThangByNgayAndHocSinhIds", hocsinhidsParameter, ngayParameter);
        }
    
        public virtual ObjectResult<user> getUser(string p_username, string p_password)
        {
            var p_usernameParameter = p_username != null ?
                new ObjectParameter("username", p_username) :
                new ObjectParameter("username", typeof(string));
    
            var p_passwordParameter = p_password != null ?
                new ObjectParameter("password", p_password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<user>("getUser", p_usernameParameter, p_passwordParameter);
        }
    
        public virtual ObjectResult<user> getUser(string p_username, string p_password, MergeOption mergeOption)
        {
            var p_usernameParameter = p_username != null ?
                new ObjectParameter("username", p_username) :
                new ObjectParameter("username", typeof(string));
    
            var p_passwordParameter = p_password != null ?
                new ObjectParameter("password", p_password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<user>("getUser", mergeOption, p_usernameParameter, p_passwordParameter);
        }
    
        public virtual ObjectResult<user_privilege> getUserPriviledgeByUserId(Nullable<int> p_userid)
        {
            var p_useridParameter = p_userid.HasValue ?
                new ObjectParameter("userid", p_userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<user_privilege>("getUserPriviledgeByUserId", p_useridParameter);
        }
    
        public virtual ObjectResult<user_privilege> getUserPriviledgeByUserId(Nullable<int> p_userid, MergeOption mergeOption)
        {
            var p_useridParameter = p_userid.HasValue ?
                new ObjectParameter("userid", p_userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<user_privilege>("getUserPriviledgeByUserId", mergeOption, p_useridParameter);
        }
    
        public virtual ObjectResult<viewbangiaotaisan> getViewBanGiaoTaiSanByLopId(Nullable<int> lopid)
        {
            var lopidParameter = lopid.HasValue ?
                new ObjectParameter("lopid", lopid) :
                new ObjectParameter("lopid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewbangiaotaisan>("getViewBanGiaoTaiSanByLopId", lopidParameter);
        }
    
        public virtual ObjectResult<viewbangiaotaisan> getViewBanGiaoTaiSanByLopId(Nullable<int> lopid, MergeOption mergeOption)
        {
            var lopidParameter = lopid.HasValue ?
                new ObjectParameter("lopid", lopid) :
                new ObjectParameter("lopid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewbangiaotaisan>("getViewBanGiaoTaiSanByLopId", mergeOption, lopidParameter);
        }
    
        public virtual ObjectResult<viewbangiaotaisan> getViewBanGiaoTaiSanByYear(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewbangiaotaisan>("getViewBanGiaoTaiSanByYear", yearParameter);
        }
    
        public virtual ObjectResult<viewbangiaotaisan> getViewBanGiaoTaiSanByYear(Nullable<int> year, MergeOption mergeOption)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewbangiaotaisan>("getViewBanGiaoTaiSanByYear", mergeOption, yearParameter);
        }
    
        public virtual ObjectResult<viewbangthutien> getViewBangThuTienByNgayTinhAndHocSinhId(Nullable<System.DateTime> p_ngay, Nullable<int> p_hocsinhid)
        {
            var p_ngayParameter = p_ngay.HasValue ?
                new ObjectParameter("ngay", p_ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var p_hocsinhidParameter = p_hocsinhid.HasValue ?
                new ObjectParameter("hocsinhid", p_hocsinhid) :
                new ObjectParameter("hocsinhid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewbangthutien>("getViewBangThuTienByNgayTinhAndHocSinhId", p_ngayParameter, p_hocsinhidParameter);
        }
    
        public virtual ObjectResult<viewbangthutien> getViewBangThuTienByNgayTinhAndHocSinhId(Nullable<System.DateTime> p_ngay, Nullable<int> p_hocsinhid, MergeOption mergeOption)
        {
            var p_ngayParameter = p_ngay.HasValue ?
                new ObjectParameter("ngay", p_ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var p_hocsinhidParameter = p_hocsinhid.HasValue ?
                new ObjectParameter("hocsinhid", p_hocsinhid) :
                new ObjectParameter("hocsinhid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewbangthutien>("getViewBangThuTienByNgayTinhAndHocSinhId", mergeOption, p_ngayParameter, p_hocsinhidParameter);
        }
    
        public virtual ObjectResult<viewbangthutien> getViewBangThuTienByNgayTinhAndLop(Nullable<System.DateTime> ngay, Nullable<int> lop)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var lopParameter = lop.HasValue ?
                new ObjectParameter("lop", lop) :
                new ObjectParameter("lop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewbangthutien>("getViewBangThuTienByNgayTinhAndLop", ngayParameter, lopParameter);
        }
    
        public virtual ObjectResult<viewbangthutien> getViewBangThuTienByNgayTinhAndLop(Nullable<System.DateTime> ngay, Nullable<int> lop, MergeOption mergeOption)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var lopParameter = lop.HasValue ?
                new ObjectParameter("lop", lop) :
                new ObjectParameter("lop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewbangthutien>("getViewBangThuTienByNgayTinhAndLop", mergeOption, ngayParameter, lopParameter);
        }
    
        public virtual ObjectResult<viewhoctap> getViewHocTapByLopAndNgay(Nullable<int> lop, Nullable<System.DateTime> ngay)
        {
            var lopParameter = lop.HasValue ?
                new ObjectParameter("lop", lop) :
                new ObjectParameter("lop", typeof(int));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewhoctap>("getViewHocTapByLopAndNgay", lopParameter, ngayParameter);
        }
    
        public virtual ObjectResult<viewhoctap> getViewHocTapByLopAndNgay(Nullable<int> lop, Nullable<System.DateTime> ngay, MergeOption mergeOption)
        {
            var lopParameter = lop.HasValue ?
                new ObjectParameter("lop", lop) :
                new ObjectParameter("lop", typeof(int));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewhoctap>("getViewHocTapByLopAndNgay", mergeOption, lopParameter, ngayParameter);
        }
    
        public virtual ObjectResult<viewtaisan> getViewTaiSanForBanGiaoTaiSan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewtaisan>("getViewTaiSanForBanGiaoTaiSan");
        }
    
        public virtual ObjectResult<viewtaisan> getViewTaiSanForBanGiaoTaiSan(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewtaisan>("getViewTaiSanForBanGiaoTaiSan", mergeOption);
        }
    
        public virtual int insertHocSinhToLop(Nullable<int> hocsinh, Nullable<int> lop, Nullable<System.DateTime> ngayvaolop)
        {
            var hocsinhParameter = hocsinh.HasValue ?
                new ObjectParameter("hocsinh", hocsinh) :
                new ObjectParameter("hocsinh", typeof(int));
    
            var lopParameter = lop.HasValue ?
                new ObjectParameter("lop", lop) :
                new ObjectParameter("lop", typeof(int));
    
            var ngayvaolopParameter = ngayvaolop.HasValue ?
                new ObjectParameter("ngayvaolop", ngayvaolop) :
                new ObjectParameter("ngayvaolop", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertHocSinhToLop", hocsinhParameter, lopParameter, ngayvaolopParameter);
        }
    
        public virtual int insertUserPrivilegeIfNotExists(Nullable<int> p_userid, Nullable<int> p_privilegeid, Nullable<int> p_value)
        {
            var p_useridParameter = p_userid.HasValue ?
                new ObjectParameter("userid", p_userid) :
                new ObjectParameter("userid", typeof(int));
    
            var p_privilegeidParameter = p_privilegeid.HasValue ?
                new ObjectParameter("privilegeid", p_privilegeid) :
                new ObjectParameter("privilegeid", typeof(int));
    
            var p_valueParameter = p_value.HasValue ?
                new ObjectParameter("value", p_value) :
                new ObjectParameter("value", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertUserPrivilegeIfNotExists", p_useridParameter, p_privilegeidParameter, p_valueParameter);
        }
    
        public virtual int insertViewBanGiaoTaiSai(Nullable<int> taisanid, Nullable<int> lopid, Nullable<System.DateTime> ngaybangiao, Nullable<System.DateTime> ngayhethan, string ghichu, Nullable<double> soluongbangiao)
        {
            var taisanidParameter = taisanid.HasValue ?
                new ObjectParameter("taisanid", taisanid) :
                new ObjectParameter("taisanid", typeof(int));
    
            var lopidParameter = lopid.HasValue ?
                new ObjectParameter("lopid", lopid) :
                new ObjectParameter("lopid", typeof(int));
    
            var ngaybangiaoParameter = ngaybangiao.HasValue ?
                new ObjectParameter("ngaybangiao", ngaybangiao) :
                new ObjectParameter("ngaybangiao", typeof(System.DateTime));
    
            var ngayhethanParameter = ngayhethan.HasValue ?
                new ObjectParameter("ngayhethan", ngayhethan) :
                new ObjectParameter("ngayhethan", typeof(System.DateTime));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            var soluongbangiaoParameter = soluongbangiao.HasValue ?
                new ObjectParameter("soluongbangiao", soluongbangiao) :
                new ObjectParameter("soluongbangiao", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertViewBanGiaoTaiSai", taisanidParameter, lopidParameter, ngaybangiaoParameter, ngayhethanParameter, ghichuParameter, soluongbangiaoParameter);
        }
    
        public virtual int insertViewTaiSan(string ten, Nullable<System.DateTime> ngaynhap, string donvitinh, Nullable<int> soluong, Nullable<long> dongia, Nullable<long> thanhtien, string sochungtu, Nullable<System.DateTime> ngaychungtu, Nullable<int> phanloaichi)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var ngaynhapParameter = ngaynhap.HasValue ?
                new ObjectParameter("ngaynhap", ngaynhap) :
                new ObjectParameter("ngaynhap", typeof(System.DateTime));
    
            var donvitinhParameter = donvitinh != null ?
                new ObjectParameter("donvitinh", donvitinh) :
                new ObjectParameter("donvitinh", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(long));
    
            var thanhtienParameter = thanhtien.HasValue ?
                new ObjectParameter("thanhtien", thanhtien) :
                new ObjectParameter("thanhtien", typeof(long));
    
            var sochungtuParameter = sochungtu != null ?
                new ObjectParameter("sochungtu", sochungtu) :
                new ObjectParameter("sochungtu", typeof(string));
    
            var ngaychungtuParameter = ngaychungtu.HasValue ?
                new ObjectParameter("ngaychungtu", ngaychungtu) :
                new ObjectParameter("ngaychungtu", typeof(System.DateTime));
    
            var phanloaichiParameter = phanloaichi.HasValue ?
                new ObjectParameter("phanloaichi", phanloaichi) :
                new ObjectParameter("phanloaichi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertViewTaiSan", tenParameter, ngaynhapParameter, donvitinhParameter, soluongParameter, dongiaParameter, thanhtienParameter, sochungtuParameter, ngaychungtuParameter, phanloaichiParameter);
        }
    
        public virtual ObjectResult<viewbangiaotaisan> selectViewBanGiaoTaiSan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewbangiaotaisan>("selectViewBanGiaoTaiSan");
        }
    
        public virtual ObjectResult<viewbangiaotaisan> selectViewBanGiaoTaiSan(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewbangiaotaisan>("selectViewBanGiaoTaiSan", mergeOption);
        }
    
        public virtual int updateSoTienTruyThuByHocSinhAndNgayUpdated(Nullable<int> hocsinhid, Nullable<System.DateTime> ngayupdated, Nullable<long> sotientruythuadded)
        {
            var hocsinhidParameter = hocsinhid.HasValue ?
                new ObjectParameter("hocsinhid", hocsinhid) :
                new ObjectParameter("hocsinhid", typeof(int));
    
            var ngayupdatedParameter = ngayupdated.HasValue ?
                new ObjectParameter("ngayupdated", ngayupdated) :
                new ObjectParameter("ngayupdated", typeof(System.DateTime));
    
            var sotientruythuaddedParameter = sotientruythuadded.HasValue ?
                new ObjectParameter("sotientruythuadded", sotientruythuadded) :
                new ObjectParameter("sotientruythuadded", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateSoTienTruyThuByHocSinhAndNgayUpdated", hocsinhidParameter, ngayupdatedParameter, sotientruythuaddedParameter);
        }
    
        public virtual int updateViewBanGiaoTaiSan(Nullable<int> taisanlopid, Nullable<int> lopid, Nullable<System.DateTime> ngaybangiao, Nullable<System.DateTime> ngayhethan, string ghichu, Nullable<double> soluongbangiao)
        {
            var taisanlopidParameter = taisanlopid.HasValue ?
                new ObjectParameter("taisanlopid", taisanlopid) :
                new ObjectParameter("taisanlopid", typeof(int));
    
            var lopidParameter = lopid.HasValue ?
                new ObjectParameter("lopid", lopid) :
                new ObjectParameter("lopid", typeof(int));
    
            var ngaybangiaoParameter = ngaybangiao.HasValue ?
                new ObjectParameter("ngaybangiao", ngaybangiao) :
                new ObjectParameter("ngaybangiao", typeof(System.DateTime));
    
            var ngayhethanParameter = ngayhethan.HasValue ?
                new ObjectParameter("ngayhethan", ngayhethan) :
                new ObjectParameter("ngayhethan", typeof(System.DateTime));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            var soluongbangiaoParameter = soluongbangiao.HasValue ?
                new ObjectParameter("soluongbangiao", soluongbangiao) :
                new ObjectParameter("soluongbangiao", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateViewBanGiaoTaiSan", taisanlopidParameter, lopidParameter, ngaybangiaoParameter, ngayhethanParameter, ghichuParameter, soluongbangiaoParameter);
        }
    
        public virtual int updateViewHocTap(Nullable<int> hoctapid, Nullable<int> hocsinhlopid, Nullable<int> songaynghithang, Nullable<System.DateTime> ngay)
        {
            var hoctapidParameter = hoctapid.HasValue ?
                new ObjectParameter("hoctapid", hoctapid) :
                new ObjectParameter("hoctapid", typeof(int));
    
            var hocsinhlopidParameter = hocsinhlopid.HasValue ?
                new ObjectParameter("hocsinhlopid", hocsinhlopid) :
                new ObjectParameter("hocsinhlopid", typeof(int));
    
            var songaynghithangParameter = songaynghithang.HasValue ?
                new ObjectParameter("songaynghithang", songaynghithang) :
                new ObjectParameter("songaynghithang", typeof(int));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateViewHocTap", hoctapidParameter, hocsinhlopidParameter, songaynghithangParameter, ngayParameter);
        }
    
        public virtual int updateViewTaiSan(string ten, Nullable<System.DateTime> ngaynhap, string donvitinh, Nullable<int> soluong, Nullable<long> dongia, Nullable<long> thanhtien, string sochungtu, Nullable<System.DateTime> ngaychungtu, Nullable<int> phanloaichi, Nullable<int> taisanid)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var ngaynhapParameter = ngaynhap.HasValue ?
                new ObjectParameter("ngaynhap", ngaynhap) :
                new ObjectParameter("ngaynhap", typeof(System.DateTime));
    
            var donvitinhParameter = donvitinh != null ?
                new ObjectParameter("donvitinh", donvitinh) :
                new ObjectParameter("donvitinh", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(long));
    
            var thanhtienParameter = thanhtien.HasValue ?
                new ObjectParameter("thanhtien", thanhtien) :
                new ObjectParameter("thanhtien", typeof(long));
    
            var sochungtuParameter = sochungtu != null ?
                new ObjectParameter("sochungtu", sochungtu) :
                new ObjectParameter("sochungtu", typeof(string));
    
            var ngaychungtuParameter = ngaychungtu.HasValue ?
                new ObjectParameter("ngaychungtu", ngaychungtu) :
                new ObjectParameter("ngaychungtu", typeof(System.DateTime));
    
            var phanloaichiParameter = phanloaichi.HasValue ?
                new ObjectParameter("phanloaichi", phanloaichi) :
                new ObjectParameter("phanloaichi", typeof(int));
    
            var taisanidParameter = taisanid.HasValue ?
                new ObjectParameter("taisanid", taisanid) :
                new ObjectParameter("taisanid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateViewTaiSan", tenParameter, ngaynhapParameter, donvitinhParameter, soluongParameter, dongiaParameter, thanhtienParameter, sochungtuParameter, ngaychungtuParameter, phanloaichiParameter, taisanidParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> countBangThuTienGenHistoryByLopAndNgayTinh(Nullable<int> lop, Nullable<System.DateTime> ngay)
        {
            var lopParameter = lop.HasValue ?
                new ObjectParameter("lop", lop) :
                new ObjectParameter("lop", typeof(int));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("countBangThuTienGenHistoryByLopAndNgayTinh", lopParameter, ngayParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> getPhieuThuForReportBCHDTC(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("getPhieuThuForReportBCHDTC", tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> getSumSoTienThuByDateRange(Nullable<System.DateTime> p_fromDate, Nullable<System.DateTime> p_toDate, string p_phanloaithuids)
        {
            var p_fromDateParameter = p_fromDate.HasValue ?
                new ObjectParameter("fromDate", p_fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var p_toDateParameter = p_toDate.HasValue ?
                new ObjectParameter("toDate", p_toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var p_phanloaithuidsParameter = p_phanloaithuids != null ?
                new ObjectParameter("phanloaithuids", p_phanloaithuids) :
                new ObjectParameter("phanloaithuids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("getSumSoTienThuByDateRange", p_fromDateParameter, p_toDateParameter, p_phanloaithuidsParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> getSumSoTienChiByDateRange(Nullable<System.DateTime> p_fromDate, Nullable<System.DateTime> p_toDate, string p_phanloaichiids)
        {
            var p_fromDateParameter = p_fromDate.HasValue ?
                new ObjectParameter("fromDate", p_fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var p_toDateParameter = p_toDate.HasValue ?
                new ObjectParameter("toDate", p_toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var p_phanloaichiidsParameter = p_phanloaichiids != null ?
                new ObjectParameter("phanloaichiids", p_phanloaichiids) :
                new ObjectParameter("phanloaichiids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("getSumSoTienChiByDateRange", p_fromDateParameter, p_toDateParameter, p_phanloaichiidsParameter);
        }
    }
}
