//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class schoolsetting
    {
        public int SchoolSettingId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateDeleted { get; set; }
    }
}
