//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class taisan_lop
    {
        public int TaiSanLopId { get; set; }
        public int TaiSanId { get; set; }
        public int LopId { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayBanGiao { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string GhiChu { get; set; }
    }
}
