//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_privilege
    {
        public int UserPrivilegeId { get; set; }
        public int UserId { get; set; }
        public int PrivilegeId { get; set; }
        public bool Value { get; set; }
    }
}
