//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class bangthutien_khoanthu
    {
        public int BTTKTId { get; set; }
        public int KhoanThuId { get; set; }
        public int BangThuTienId { get; set; }
        public long SoTien { get; set; }
    }
}
