//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class bangthutiengenhistory
    {
        public int BTTGenHistoryId { get; set; }
        public System.DateTime NgayTinh { get; set; }
        public Nullable<int> LopId { get; set; }
        public double SoTienAnSang { get; set; }
        public double SoTienAnToi { get; set; }
        public double SoTienAnChinh { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
