//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class baocaothang
    {
        public int BaoCaoThangId { get; set; }
        public System.DateTime NgayTinh { get; set; }
        public int HocTapId { get; set; }
        public int SoNgayNghi { get; set; }
    }
}
