//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class hocsinh
    {
        public int HocSinhId { get; set; }
        public string HoDem { get; set; }
        public string Ten { get; set; }
        public sbyte GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<System.DateTime> NgayVaoLop { get; set; }
        public string DanToc { get; set; }
        public string DienCuTru { get; set; }
        public string DienThoai { get; set; }
        public string HoTenCha { get; set; }
        public string HoTenMe { get; set; }
        public string DienThoaiMe { get; set; }
        public Nullable<int> TinhThanhPhoId { get; set; }
        public Nullable<int> QuanHuyenId { get; set; }
        public Nullable<int> PhuongXaId { get; set; }
        public string DiaChi { get; set; }
        public bool ThoiHoc { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }

        [NotMapped]
        public int STT { get; set; }

        [NotMapped]
        public string HoTen { get { return $"{HoDem} {Ten}"; } }

        [NotMapped]
        public string LopDangHoc { get; set; }

        [NotMapped]
        public string PhuongXa { get; set; }

        [NotMapped]
        public string QuanHuyen { get; set; }
    }
}
