//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class khoi
    {
        public int KhoiId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        [NotMapped]
        public int? TruongId { get; set; }
    }
}
