//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class phanloaichi
    {
        public int PhanLoaiChiId { get; set; }
        public string MaPhanLoai { get; set; }
        public string DienGiai { get; set; }
    }
}
