//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class smstemplate
    {
        public int SmsTemplateId { get; set; }
        public string Template { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
