//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class viewtaisan
    {
        public int TaiSanId { get; set; }
        public string Ten { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public string DonViTinh { get; set; }
        public double SoLuong { get; set; }
        public long DonGia { get; set; }
        public string SoChungTu { get; set; }
        public System.DateTime NgayChungTu { get; set; }
        public long ThanhTien { get; set; }
        public int PhieuChiId { get; set; }
        public int PhanLoaiChiId { get; set; }

        [NotMapped]
        public string PhanLoaiTaiSan { get; set; }
    }
}
