//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class viewbangthutien
    {
        public int BangThuTienId { get; set; }
        public int HocSinhId { get; set; }
        public int LopId { get; set; }
        public Nullable<int> SXThangTruoc { get; set; }
        public Nullable<long> SoTienSXThangTruoc { get; set; }
        public Nullable<int> AnSangThangTruoc { get; set; }
        public Nullable<long> SoTienAnSangThangTruoc { get; set; }
        public long SoTienAnSangThangNay { get; set; }
        public int AnToiThangTruoc { get; set; }
        public Nullable<long> SoTienAnToiThangTruoc { get; set; }
        public long SoTienAnToiThangNay { get; set; }
        public Nullable<long> SoTienNangKhieu { get; set; }
        public Nullable<long> SoTienTruyThu { get; set; }
        public Nullable<long> SoTienDoDung { get; set; }
        public Nullable<long> SoTienDieuHoa { get; set; }
        public System.DateTime NgayTinh { get; set; }
        public int STT { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long SoTienAnSangConLai { get; set; }
        public long SoTienAnToiConLai { get; set; }
        public long ThanhTien { get; set; }
        public long TienAnSua { get; set; }
        public long TienSua { get; set; }
        public long PhuPhi { get; set; }
        public long BanTru { get; set; }
        public long HocPhi { get; set; }
        public long KhoanThuChinh { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgayNopLan1 { get; set; }
        public long SoTienNopLan1 { get; set; }
        public Nullable<System.DateTime> NgayNopLan2 { get; set; }
        public long SoTienNopLan2 { get; set; }
        public string GhiChu { get; set; }
        public string Lop { get; set; }
        public string SoBienLai { get; set; }
        public string TongThu { get; set; }
        public long TienAn { get; set; }

        [NotMapped]
        public long PhucVuBanTru { get; set; }
    }
}
