//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMamNon.Dao
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class viewbangiaotaisan
    {
        public int TaiSanId { get; set; }
        public string Ten { get; set; }
        public string DonViTinh { get; set; }
        public double SoLuong { get; set; }
        public long DonGia { get; set; }
        public string SoChungTu { get; set; }
        public System.DateTime NgayChungTu { get; set; }
        public int PhieuChiId { get; set; }
        public Nullable<int> LopId { get; set; }
        public Nullable<System.DateTime> NgayBanGiao { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TaiSanLopId { get; set; }
        public Nullable<double> SoLuongBanGiao { get; set; }
        public System.DateTime NgayNhap { get; set; }

        [NotMapped]
        public string LopName { get; set; }
    }
}
